networks:
  api-network:
    external: true


services:
  sweety-api:
    container_name: sweety-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./edge_reasume_certs:/certs:ro
    env_file:
      - .env
    environment:
      - PGUSER= ${POSTGRES_USER}
      - PGHOST= ${POSTGRES_HOST}
      - PGDATABASE= ${POSTGRES_DATABASE}
      - PGPASSWORD= ${POSTGRES_PASSWORD}
      - PGPORT= ${POSTGRES_PORT}
      - MYSQL_ROOT_PASSWORD= ${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE= ${MYSQL_DATABASE}
      - MYSQL_USER= ${MYSQL_USER}
      - MYSQL_PASSWORD= ${MYSQL_PASSWORD}
      - MYSQL_HOST= ${MYSQL_HOST}
      - MYSQL_PORT= ${MYSQL_PORT}
      - TZ=Africa/Johannesburg
    ports:
      - 8083:8443
      - 8093:8080
    restart: unless-stopped
    networks:
      - api-network
